GET http://localhost:3000/admin/1337/

###
GET http://localhost:3000/admin/1337/hello?name=Matthias

###
GET http://localhost:3000/admin/123/

###
GET http://localhost:3000/admin/123/hello?name=Matthias

###
